### ISSUE TITLE
use logging module rather than print

### ISSUE THREAD

**Issue by garymcwilliams** [garymcwilliams/icalendar#20]
replace all print statements with logging module.

set base console logger as the simplest
```
  brief:
    format: '%(message)s'
  console:
    formatter: brief
```
